
node('jenkins-agent-gh-docker') {
    stage('checkout scm') {
        cleanWs()
        checkout scm
    }

    def isAnyParams = params.size() != 0

    stage("properties") {
        load('config.groovy')
        properties([
            parameters(gh_actions_params_keys.collect {
                all_params[it]
            }),
        ])
    }

    if(isAnyParams) {
        stage('gh actions') {
            withCredentials([string(credentialsId: 'rvck_gh_token', variable: 'GH_TOKEN')]) {
                def all_label_str = all_label.join(',')
                withEnv([
                    "CONFIG_all_labels=${all_label_str}"
                ]) {
                    sh 'bash gh_actions/run.sh'
                }
            }
        }
    }
}
